# Generated by Django 5.2.1 on 2025-06-01 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('Jadwal', models.CharField(max_length=255)),
                ('mulai', models.TimeField(blank=True, null=True)),
                ('akhir', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jadwal',
                'db_table': 'jadwal',
            },
        ),
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=255)),
                ('Tipe', models.CharField(max_length=255)),
                ('Jenis', models.CharField(max_length=255)),
                ('Harga', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('gambar', models.FileField(blank=True, null=True, upload_to='project_images/')),
            ],
            options={
                'verbose_name_plural': 'Lapangan',
                'db_table': 'lapangan',
            },
        ),
        migrations.CreateModel(
            name='PesananTambahan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Pesanan Tambahan',
                'db_table': 'pesanan_tambahan',
            },
        ),
        migrations.CreateModel(
            name='Tambahan',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=255)),
                ('Harga', models.IntegerField()),
                ('gambar', models.FileField(blank=True, null=True, upload_to='project_images/')),
            ],
            options={
                'verbose_name_plural': 'Tambahan',
                'db_table': 'tambahan',
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Level', models.CharField(default='user', max_length=5)),
                ('Alamat', models.TextField(blank=True, null=True)),
                ('Telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('NIP', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gambar', models.FileField(blank=True, null=True, upload_to='project_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Pengguna',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=20)),
                ('Telepon', models.CharField(max_length=20)),
                ('Jam', models.TimeField()),
                ('durasi', models.IntegerField()),
                ('Tanggal', models.DateField()),
                ('total_harga', models.IntegerField()),
                ('bayar', models.IntegerField()),
                ('kembali', models.IntegerField()),
                ('status', models.IntegerField()),
                ('ID_lapangan', models.ForeignKey(db_column='ID_lapangan', on_delete=django.db.models.deletion.CASCADE, to='accounts.lapangan')),
                ('id_jadwal', models.ForeignKey(db_column='id_jadwal', on_delete=django.db.models.deletion.CASCADE, to='accounts.jadwal')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tambahan', models.ForeignKey(db_column='id_tambahan', on_delete=django.db.models.deletion.CASCADE, to='accounts.pesanantambahan')),
            ],
            options={
                'verbose_name_plural': 'Pesanan',
                'db_table': 'pesanan',
            },
        ),
        migrations.AddField(
            model_name='pesanantambahan',
            name='id_tambahan',
            field=models.ForeignKey(db_column='id_tambahan', on_delete=django.db.models.deletion.CASCADE, to='accounts.tambahan'),
        ),
    ]
