# Generated by Django 5.2.1 on 2025-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengguna',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='lapangan',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to='lapangan_images/'),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='tambahan',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to='tambahan_images/'),
        ),
    ]
